name: Build

on:
  push:
    branches:
      - master
  pull-request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        java: [8, 11, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ java }}
      - name: Build and Test
        run: ./gradlew clean build test