name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        java: [8, 11, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build
        run: ./gradlew clean build test --stacktrace
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-report-${{ matrix.os }}-java-${{ matrix.java }}
          path: build/reports/tests/test/